name: MarketPlus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  firebase_auth: ^0.8.1+4
  firebase_core: ^0.3.1+1
  google_sign_in: ^4.4.4
  flutter_auth_buttons: ^0.3.1
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.0
  http: ^0.12.2
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/

